language: go
go:
  - 1.19.x
script:
  - go get -v
  - make test
  - make compile
deploy:
  provider: releases
  api_key:
    secure: Q/cf9v4XZjrTlFZH7DIlH4XusBA+KzZKjmKtxB8nK5HMS9E6toIXK8VIj0MoIOkng6PCqY2EL60kVksIE6S6mtRi3wtq27ahpAxbcKtDgpilTQJRDir/kUnAWKmJQO/nqmNUwiv6seKCA5T11gr7rmpIxNWJUMmcw40MYminIBPoPfA/WfRlcoO+pf5NMvXetd28LNiTKx431XQKILzEEXmQjMy4CwkQ3eWbfXmPJSZC/nGnW6TnLvAlvo4iMobIoCLyxkVR6Nb5BVLrVZbbvCfp9A7XSo0DzJxFpTQr9b0GO2XXCDKhDpe1MRpJiC3hOeTQBHbkESAMTSCqq9DoFFBB66C7yzlhS/u1NNIMVduIQnP9cXX/WXsi/hx66Ba8lTOWp+tmOnv0lzvR0AKEq9CWg1Fzlve1Lmr9PSOSqgolSFpHj1BpLuTF9aAPPsMamdelvKOjv6kyUO6TUEeSKwmf4lK33P7IUlBT0bBLn7UmGT0lEXMRHS7Il5HRx/QhH11Jm6eA+xO1zaHGi24L/AtgJbItkDYMIB2/9QCqP/WhtirU6gB2OMC3538T2BUalWjyWLG6DdLoezINNaubi+Twnv1v2T5ApAMhKYLT3tDjtQLTyB13Qf7YDhicFLv3IPvYnu5uLeju40muU6YbLFNEEmsX7rl/vny2rqSiIg0=
  file:
    - bin/ionosphere-freebsd-amd64.tar.gz
    - bin/ionosphere-linux-amd64.tar.gz
    - bin/ionosphere-macos-amd64.tar.gz
    - bin/ionosphere-macos-arm64.tar.gz
    - bin/ionosphere-raspberry-pi.tar.gz
    - bin/ionosphere-windows-amd64.zip
  skip_cleanup: true
  draft: true
  on:
    tags: true
